@echo off
echo Arrancando Servidor y Cliente en ventanas independientes...

echo Iniciando Servidor Backend...
start "Servidor Backend" cmd /k "cd /d %~dp0app-seguimiento\server && node server.js"

echo Iniciando Cliente Frontend...
start "Cliente Frontend" cmd /k "cd /d %~dp0app-seguimiento-cliente\client && npm run dev"

echo Esperando a que los servicios se inicien...
timeout /t 3 /nobreak > nul

echo Abriendo navegador...
start "" "http://localhost:5173"
